version: '3'
services:
  web:
    build: .
    ports:
      - "9500:9500"
    environment:
      - PORT=9500
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

